#!/bin/bash

sudo apt update
#install if not installed MySQL client, p7zip, python3.6, python-pip
sudo apt install -y mysql-client p7zip python3.6 python-pip

#instal python pdf library
pip install dbfpy

