#!/bin/bash

set -e

#Include configuration file
source update_kladr.config

#Clear previous files
rm -rf tmp

#Download kladr in archive
mkdir tmp
cd tmp
curl -o base.7z $url

#Unzip kladr files
p7zip -d base.7z

#Convert kladr files to csv with utf-8 encoding
for a in ${tables[@]}
do
  #Convert to csv using pyton script 
  python ../dbf2csv.py $a.dbf

  #Convert to utf-8
  iconv -f cp866 -t $dest_encoding $a.csv >${a}_utf8.csv
done


#Import csv to MySQL database
for i in ${!tables[@]}
do
    #Get table name from config
    ta=${tables_aliases[$i]}
    tsource=${tables[$i]}

    #Skip if table name is 'skip'
    if [ $ta = "skip" ]
    then
        echo "[$tsource]: skipped"
        continue
    fi

    #Create table if it not exist with script from config file. Or clear exist table. Load data from csv to table
    echo "[$tsource]: start update"
    cquery="${create_tables[$i]}"
    mysql -h $host -u "$user" -p"$password" --database=$database --execute="$cquery; TRUNCATE $ta; LOAD DATA LOCAL INFILE '$PWD/${tsource}_utf8.csv' INTO TABLE $ta FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n' IGNORE 1 LINES;"
    echo "[$tsource]: finish update"
done
