#!/bin/bash

set -e

source update_kladr.conf

#m -rf tmp
#kdir tmp
cd tmp
#url -o base.7z $url
#7zip -d base.7z

#or a in ${tables[@]}
#o
  #ython ../dbf2csv.py $a.dbf
  #conv -f cp866 -t $dest_encoding $a.csv >${a}_utf8.csv
#one



for i in ${!tables[@]}
do
    ta=${tables_aliases[$i]}
    cquery="${create_tables[$i]}"
    mysql -h $host -u "$user" -p"$password" --database=$database --execute="$cquery; TRUNCATE $ta;"
done
