#!/bin/bash

set -e

source update_kladr.config

#rm -rf tmp
#mkdir tmp
cd tmp
#curl -o base.7z $url
#p7zip -d base.7z

#for a in ${tables[@]}
#do
  #python ../dbf2csv.py $a.dbf
  #iconv -f cp866 -t $dest_encoding $a.csv >${a}_utf8.csv
#done



for i in ${!tables[@]}
do
    ta=${tables_aliases[$i]}
    tsource=${tables[$i]}
    if [ $ta = "skip" ]
    then
        echo "[$tsource]: skipped"
        continue
    fi
    echo "[$tsource]: start update"
    cquery="${create_tables[$i]}"
    mysql -h $host -u "$user" -p"$password" --database=$database --execute="$cquery; TRUNCATE $ta; LOAD DATA LOCAL INFILE '$PWD/${tsource}_utf8.csv' INTO TABLE $ta FIELDS TERMINATED BY ',' ENCLOSED BY '\"' LINES TERMINATED BY '\n' IGNORE 1 LINES;"
    echo "[$tsource]: finish update"
done
